/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESSAGE_PB_H_INCLUDED
#define PB_MESSAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _LoRaMessage {
    uint32_t type;
    uint32_t message_id;
    uint32_t encrypted_path;
    int32_t goal_dm_speed;
    int32_t degrees_per_sec;
} LoRaMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define LoRaMessage_init_default                 {0, 0, 0, 0, 0}
#define LoRaMessage_init_zero                    {0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define LoRaMessage_type_tag                     1
#define LoRaMessage_message_id_tag               2
#define LoRaMessage_encrypted_path_tag           3
#define LoRaMessage_goal_dm_speed_tag            10
#define LoRaMessage_degrees_per_sec_tag          11

/* Struct field encoding specification for nanopb */
#define LoRaMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type,              1) \
X(a, STATIC,   SINGULAR, UINT32,   message_id,        2) \
X(a, STATIC,   SINGULAR, UINT32,   encrypted_path,    3) \
X(a, STATIC,   SINGULAR, SINT32,   goal_dm_speed,    10) \
X(a, STATIC,   SINGULAR, SINT32,   degrees_per_sec,  11)
#define LoRaMessage_CALLBACK NULL
#define LoRaMessage_DEFAULT NULL

extern const pb_msgdesc_t LoRaMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define LoRaMessage_fields &LoRaMessage_msg

/* Maximum encoded size of messages (where known) */
#define LoRaMessage_size                         30
#define MESSAGE_PB_H_MAX_SIZE                    LoRaMessage_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
